//! Operations that allow Cyclone to interact with Rust allocated data
//! structures. These are threaded through the [`Sertype`] type.

use std::ffi::CStr;
use std::hash::{Hash, Hasher};

use crate::internal::ffi::InternalSample;
use crate::internal::ffi::serdata_ops::DDSI_RTPS_HEADER_SIZE;
use crate::internal::sertype::Sertype;
use crate::internal::traits::CdrHeader;

/// A version to allow Cyclone DDS to ensure backwards compatibility if breaking
/// changes to the sertype API are introduced.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
#[non_exhaustive]
pub enum SertypeVersion {
    V0,
}

impl SertypeVersion {
    // NOTE: the wrapping for this in an option just comes from the layout of
    // `ddsi_sertype_v0_t` as generated by Cyclone DDS. There isn't really a
    // benefit to removing the `Option` to just add it back immediately in the one
    // callsite.
    #[allow(clippy::unnecessary_wraps)]
    pub(crate) const fn as_ffi(self) -> cyclonedds_sys::ddsi_sertype_v0_t {
        match self {
            SertypeVersion::V0 => {
                #[cfg(not(target_family = "windows"))]
                {
                    Some(cyclonedds_sys::ddsi_sertype_v0)
                }
                #[cfg(target_family = "windows")]
                {
                    // NOTE: Windows does not have the `dds_sertype_v0` constant exposed and the
                    // underlying value that v0 expects in the C lib for that
                    // platform is 0x01 cast to a function pointer.
                    //
                    // This cannot be created in Rust as a function pointer because the const
                    // evaluator rejects 0x01 as a valid function pointer so the `-sys` crate
                    // intercepts the type under Windows and exposes a compatible type definition
                    // with the same niche-optimization as Option<fn()> i.e. Option<NonZeroUsize>.
                    //
                    // I can then safely (internally) create this value which should be interpreted
                    // equivalently on the Windows side as if I had passed the 0x01 function
                    // pointer.
                    std::num::NonZeroUsize::new(1)
                }
            }
        }
    }
}

/// Arbitrary metadata that was originally used for backwards compatibility as
/// part of the `sertopic` -> `sertype` changeover.
pub const ARG: *mut std::ffi::c_void = std::ptr::null_mut();

/// A flag specifying that the data representation in use corresponds to XCDR1.
#[allow(unused)]
pub const DATA_REPRESENTATION_XCDR1: u32 = cyclonedds_sys::DDS_DATA_REPRESENTATION_XCDR1;
/// A flag specifying that the data representation in use corresponds to XCDR2.
#[allow(unused)]
pub const DATA_REPRESENTATION_XCDR2: u32 = cyclonedds_sys::DDS_DATA_REPRESENTATION_XCDR2;

/// This exists to ensure that initializing `cyclonedds_sys::ddsi_sertype_ops`
/// will work in const contexts even if more fields are added down the line to
/// Cyclone DDS.
pub(crate) const fn zeroed_sertype_ops() -> cyclonedds_sys::ddsi_sertype_ops {
    // SAFETY: `cyclonedds_sys::ddsi_sertype_ops` is repr(C) and consists solely of
    // function pointers and various integer types.
    unsafe { std::mem::MaybeUninit::zeroed().assume_init() }
}

/// Free a [`Sertype`] created on the Rust side of the FFI.
///
/// ## Safety
/// The provided `sertype` pointer must be from the pointer embedded in a
/// [`Sertype`] that was created via [`Sertype::new`].
pub unsafe extern "C" fn free<T>(sertype: *mut cyclonedds_sys::ddsi_sertype)
where
    T: crate::Topicable,
{
    let sertype = unsafe { Box::from_raw(sertype.cast::<Sertype<T>>()) };
    drop(sertype);
}

///
/// TODO: validate what the purpose of this is in the actual functioning of
/// Cyclone? The C++ API also maps this to a no-op.
pub unsafe extern "C" fn zero_samples<T>(
    _sertype: *const cyclonedds_sys::ddsi_sertype,
    samples: *mut std::ffi::c_void,
    count: usize,
) where
    T: crate::Topicable,
{
    let samples = samples.cast::<InternalSample<'_, T>>();

    for i in 0..count {
        unsafe {
            let pointer = samples.add(i);
            pointer.write(InternalSample::None);
        }
    }
}

/// Realloc the sample buffer.
pub unsafe extern "C" fn realloc_samples<T>(
    pointers: *mut *mut std::ffi::c_void,
    _sertype: *const cyclonedds_sys::ddsi_sertype,
    old_samples: *mut std::ffi::c_void,
    old_count: usize,
    new_count: usize,
) where
    T: crate::Topicable,
{
    let pointers = pointers.cast::<*mut InternalSample<'_, T>>();
    let old_samples = old_samples.cast::<InternalSample<'_, T>>();

    let pointers = unsafe { std::slice::from_raw_parts_mut(pointers, new_count) };

    // Copy over initial samples.
    if !old_samples.is_null() && old_count != 0 {
        let old_samples = unsafe { std::slice::from_raw_parts_mut(old_samples, old_count) };

        let count = old_count.min(new_count);

        // Split into samples to keep and samples to drop
        let (samples_to_keep, samples_to_drop) = old_samples.split_at_mut(count);

        // Move retained samples
        for (pointer, sample) in pointers.iter_mut().zip(samples_to_keep.iter()) {
            let sample = unsafe { std::ptr::read(sample) };
            *pointer = Box::into_raw(Box::new(sample));
        }

        // If it's shrinking.
        for sample in samples_to_drop {
            unsafe { std::ptr::drop_in_place(sample) };
        }

        #[allow(clippy::indexing_slicing)]
        // `count <= pointers.len()` as `count` is the minimum of `new_count`
        // (which `pointers` was created with) and `old_count`.
        let remaining_slots = &mut pointers[count..];

        // Allocate new samples for additional slots
        for pointer in remaining_slots {
            *pointer = Box::into_raw(Box::new(InternalSample::None));
        }
    } else {
        // Allocate new samples for additional slots
        for pointer in pointers {
            *pointer = Box::into_raw(Box::new(InternalSample::None));
        }
    }
}

/// Free previously allocated samples.
///
/// Release any memory allocated by
/// [`serdata_ops::to_sample`][`crate::internal::ffi::serdata_ops::to_sample`].
///
/// ## Safety
/// `pointers` must be non-null and must point to a valid pointer that was
/// allocated via a `Box<T>`.
pub unsafe extern "C" fn free_samples<T>(
    _sertype: *const cyclonedds_sys::ddsi_sertype,
    pointers: *mut *mut std::ffi::c_void,
    count: usize,
    operation: cyclonedds_sys::dds_free_op_t,
) where
    T: crate::Topicable,
{
    // NOTE: `operation` is an enum with a different backing type under Windows
    // (i32) and the rest of the operating systems (u32). For the Rust API I've
    // chosen to standardize its internal representation against u32 and so the
    // cast is necessary under Windows and essentially a no-op under the other
    // platforms.
    #[allow(clippy::unnecessary_cast, clippy::cast_sign_loss)]
    let operation = operation as u32;

    let free_all = operation & cyclonedds_sys::DDS_FREE_ALL_BIT != 0;
    let free_contents = operation & cyclonedds_sys::DDS_FREE_CONTENTS_BIT != 0;
    let samples = pointers.cast::<*mut InternalSample<'_, T>>();

    if free_all {
        for i in 0..count {
            let sample = unsafe { Box::from_raw(*samples.add(i)) };
            drop(sample);
        }
    } else if free_contents {
        for i in 0..count {
            unsafe {
                (*samples.add(i)).drop_in_place();
            }
        }
    }
}

/// Compares two [`Sertype`] instances for equality.
///
/// # Safety
/// - The `lhs` and `rhs` must point to `Sertype`s previously constructed by the
///   Rust API.
/// - The `type_name` field of the pointers must be a valid null-terminated
///   string.
pub unsafe extern "C" fn equal<T>(
    lhs: *const cyclonedds_sys::ddsi_sertype,
    rhs: *const cyclonedds_sys::ddsi_sertype,
) -> bool
where
    T: crate::Topicable,
{
    let lhs = std::mem::ManuallyDrop::new(unsafe { Box::from_raw(lhs as *mut Sertype<T>) });
    let rhs = std::mem::ManuallyDrop::new(unsafe { Box::from_raw(rhs as *mut Sertype<T>) });

    // Also base this on the type support identifier?
    unsafe { CStr::from_ptr(lhs.inner.type_name) == CStr::from_ptr(rhs.inner.type_name) }
}

/// Compute a hash for a DDS data type.
///
/// # Safety
/// The provided `sertype` must be a valid sertype created through
/// [`Sertype::new`].
pub unsafe extern "C" fn hash<T>(sertype: *const cyclonedds_sys::ddsi_sertype) -> u32
where
    T: crate::Topicable,
{
    let sertype = std::mem::ManuallyDrop::new(unsafe { Box::from_raw(sertype as *mut Sertype<T>) });

    let name = unsafe { CStr::from_ptr(sertype.inner.type_name) };
    let type_size = std::mem::size_of::<T>();

    // Prepare the 32-bit hash by running the default hasher which produces a
    // 64-bit output and then combining the high and low ends of the hash via
    // xor to produce a 32-bit output.
    let mut hasher = std::hash::DefaultHasher::new();
    name.hash(&mut hasher);
    type_size.hash(&mut hasher);
    let hash: u64 = hasher.finish();

    // Do a 64-bit fold of both halves of the hash.
    //
    // NOTE: that the truncation to 32 bits is intentional and because of the
    // fold no entropy should be lost.
    #[allow(clippy::cast_possible_truncation)]
    let hash: u32 = (hash ^ (hash >> 32)) as u32;

    hash
}

/// TODO Unimplemented.
/// # Safety
#[allow(unused)]
pub unsafe extern "C" fn type_id<T>(
    sertype: *const cyclonedds_sys::ddsi_sertype,
    kind: cyclonedds_sys::ddsi_typeid_kind_t,
) -> *mut cyclonedds_sys::ddsi_typeid
where
    T: crate::Topicable,
{
    let args = (sertype, kind);
    eprintln!(
        "sertype_ops::type_id<{}>({args:?})",
        std::any::type_name::<T>()
    );

    std::ptr::null_mut()
}

/// TODO Unimplemented.
/// # Safety
#[allow(unused)]
pub unsafe extern "C" fn type_map<T>(
    sertype: *const cyclonedds_sys::ddsi_sertype,
) -> *mut cyclonedds_sys::ddsi_typemap
where
    T: crate::Topicable,
{
    let args = sertype;
    eprintln!(
        "sertype_ops::type_map<{}>({args:?})",
        std::any::type_name::<T>()
    );
    std::ptr::null_mut()
}

/// TODO Unimplemented.
/// # Safety
#[allow(unused)]
pub unsafe extern "C" fn type_info<T>(
    sertype: *const cyclonedds_sys::ddsi_sertype,
) -> *mut cyclonedds_sys::ddsi_typeinfo
where
    T: crate::Topicable,
{
    let args = sertype;
    eprintln!(
        "sertype_ops::type_info<{}>({args:?})",
        std::any::type_name::<T>()
    );
    std::ptr::null_mut()
}

/// TODO Unimplemented.
/// # Safety
#[allow(unused)]
pub unsafe extern "C" fn derive_sertype<T>(
    sertype: *const cyclonedds_sys::ddsi_sertype,
    data_representation: cyclonedds_sys::dds_data_representation_id_t,
    type_consistency_enforcement_qos: cyclonedds_sys::dds_type_consistency_enforcement_qospolicy,
) -> *mut cyclonedds_sys::ddsi_sertype
where
    T: crate::Topicable,
{
    let args = (
        sertype,
        data_representation,
        type_consistency_enforcement_qos,
    );
    eprintln!(
        "sertype_ops::derive_sertype<{}>({args:?})",
        std::any::type_name::<T>()
    );

    std::ptr::null_mut()
}

/// TODO Unimplemented.
/// # Safety
pub unsafe extern "C" fn get_serialized_size<T>(
    sertype: *const cyclonedds_sys::ddsi_sertype,
    serdata_kind: cyclonedds_sys::ddsi_serdata_kind,
    sample: *const std::ffi::c_void,
    size: *mut usize,
    encoding_identifier: *mut u16,
) -> i32
where
    T: crate::Topicable,
{
    let args = (sertype, serdata_kind, sample, size, encoding_identifier);
    eprintln!(
        "sertype_ops::get_serialized_size<{}>({args:?})",
        std::any::type_name::<T>()
    );
    0
}

///
/// # Safety
pub unsafe extern "C" fn serialize_into<T>(
    _sertype: *const cyclonedds_sys::ddsi_sertype,
    serdata_kind: cyclonedds_sys::ddsi_serdata_kind,
    sample: *const std::ffi::c_void,
    destination_buffer: *mut std::ffi::c_void,
    destination_buffer_length: usize,
) -> bool
where
    T: crate::Topicable,
{
    let buffer = unsafe {
        std::slice::from_raw_parts_mut(destination_buffer.cast(), destination_buffer_length)
    };

    if let Some(header) = buffer.get_mut(0..DDSI_RTPS_HEADER_SIZE) {
        header.copy_from_slice(&byteorder::NativeEndian::cdr_header());
    } else {
        return false;
    }

    if sample.is_null() {
        false
    } else {
        let sample = unsafe { &*(sample.cast::<InternalSample<'_, T>>()) };
        // TODO verify if the to_writer interface errors if it reaches the bounds of the
        // buffer.
        match (
            crate::internal::serdata::Kind::try_from(serdata_kind),
            sample,
        ) {
            (Ok(crate::internal::serdata::Kind::Data), InternalSample::Sample(sample)) => buffer
                .get_mut(DDSI_RTPS_HEADER_SIZE..)
                .is_some_and(|bytes| {
                    cdr_encoding::to_writer::<_, byteorder::NativeEndian, _>(bytes, sample).is_ok()
                }),
            (Ok(crate::internal::serdata::Kind::Key), InternalSample::Key(key)) => buffer
                .get_mut(DDSI_RTPS_HEADER_SIZE..)
                .is_some_and(|bytes| {
                    cdr_encoding::to_writer::<_, byteorder::NativeEndian, _>(bytes, key).is_ok()
                }),
            _ => false,
        }
    }
}
